# Site settings
title: "Mounib Mohamed El Mahdi"
email: "mounibmohamedelmahdi@gmail.com"
description: "Senior Technical Supervisor | IT, BMS & Smart Mobility Expert"
baseurl: ""
url: "https://Mehdimnb.github.io"

# Social links
github_username: "Mehdimnb"
linkedin_username: "mahdi-mnb"

# Build settings
markdown: kramdown
